dist: trusty

language: php

env:
    global:
        - APP_ENV=test
        - APP_NAME_CACHE_DIR=$HOME/.app_name-cache
        - APP_NAME_BUILD_DIR=etc/build
        - MYSQL_HOST=127.0.0.1
        - MYSQL_USER=root
        - MYSQL_PASSWORD=
        - MYSQL_DATABASE=application_test

matrix:
    include:
        -
            sudo: required
            php: 7.2
            env:
                - APP_NAME_SUITE="application"
                - TRAVIS_NODE_VERSION="7.5"
            services:
                - memcached
        -
            name: "Docker build"

            sudo: required

            env:
                - DOCKER_COMPOSE_VERSION=1.22.0
                - APP_NAME_SUITE="docker"

            services:
                - docker

            addons:
                apt:
                    packages:
                        - docker-ce

            before_install:
              # Install custom version of docker-composer
                - sudo rm /usr/local/bin/docker-compose
                - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
                - chmod +x docker-compose
                - sudo mv docker-compose /usr/local/bin

                # Shutdown vanilla mysql
                - sudo service mysql stop
                - while sudo lsof -Pi :3306 -sTCP:LISTEN -t; do sleep 1; done

            script:
                - id
                - docker-compose --version
                - docker-compose -f docker-compose.yml -f etc/travis/docker-compose.override.yml pull --ignore-pull-failures || true
                - docker-compose -f docker-compose.yml -f etc/travis/docker-compose.override.yml  build --pull
                - docker-compose -f docker-compose.yml -f etc/travis/docker-compose.override.yml up -d

                - sleep 60

                - docker-compose -f docker-compose.yml -f etc/travis/docker-compose.override.yml logs --no-color --tail=100000

                - curl http://localhost/
        -
            sudo: false
            php: 7.2
            env: APP_NAME_SUITE="docs packages"
            addons:
                apt:
                    packages:
                        - parallel

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - ~/.cache/pip
        - vendor
        - node_modules
        - $APP_NAME_CACHE_DIR

before_install:
    - etc/travis/run-suite before_install "${APP_NAME_SUITE}"

install:
    - etc/travis/run-suite install "${APP_NAME_SUITE}"

before_script:
    - etc/travis/run-suite before_script "${APP_NAME_SUITE}"

script:
    - etc/travis/run-suite script "${APP_NAME_SUITE}"

before_cache:
    - etc/travis/run-suite before_cache "${APP_NAME_SUITE}"

after_success:
    - etc/travis/run-suite after_success "${APP_NAME_SUITE}"

after_failure:
    - etc/travis/run-suite after_failure "${APP_NAME_SUITE}"

after_script:
    - etc/travis/run-suite after_script "${APP_NAME_SUITE}"

notifications:
    email: false
